- name: Pull Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    source: pull

- name: Run Docker container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    ports: "{{ docker_container_ports }}"
