---
- name: Install Docker and Nginx, Deploy Docker Image
  hosts: azure_vms
  become: yes
  roles:
    - role: docker_nginx
      vars:
        docker_packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        docker_nginx_service_name: nginx
    - role: deploy_image
      vars:
        docker_image_name: nginx
        docker_container_name: nginx_container
        docker_container_ports:
          - "50:80"
